package enums

const (
	POSTGRESQL_DB       = "POSTGRESQL_DB"
	POSTGRESQL_USER     = "POSTGRESQL_USER"
	POSTGRESQL_PASSWORD = "POSTGRESQL_PASSWORD"
	POSTGRESQL_HOST     = "POSTGRESQL_HOST"
	POSTGRESQL_PORT     = "POSTGRESQL_PORT"
	POSTGRESQL_DB_URL   = "POSTGRESQL_DB_URL"
)
const (
	APP_NAME = "APP_NAME"
	ENV      = "ENV"
	PORT     = "PORT"
	TIMEZONE = "TIMEZONE"
)

const (
	MODE = "MODE"

	SERVER      = "server"
	DEVELOPMENT = "development"
)

const (
	DEV        = "DEV"
	UAT        = "UAT"
	PRODUCTION = "PRODUCTION"
)

const (
	REDIS_SERVER = "REDIS_SERVER"
)

const (
	SSH_USER                  = "SSH_USER"
	SSH_PRIVATE_KEY_FILE_PATH = "SSH_PRIVATE_KEY_FILE_PATH"
	SSH_HOST                  = "SSH_HOST"
	SSH_PORT                  = "22"
)
