package enums

const (
	POSTGRESQL_DB       = "POSTGRESQL_DB"
	POSTGRESQL_USER     = "POSTGRESQL_USER"
	POSTGRESQL_PASSWORD = "POSTGRESQL_PASSWORD"
	POSTGRESQL_HOST     = "POSTGRESQL_HOST"
	POSTGRESQL_PORT     = "POSTGRESQL_PORT"
)
const (
	APP_NAME = "APP_NAME"
	ENV      = "ENV"
	MODE     = "MODE"
	PORT     = "PORT"
	TIMEZONE = "TIMEZONE"
)

const (
	SERVER      = "SERVER"
	DEVELOPMENT = "DEVELOPMENT"
)

const (
	DEV        = "DEV"
	UAT        = "UAT"
	PRODUCTION = "PRODUCTION"
)

const (
	REDIS_SERVER = "REDIS_SERVER"
)

const (
	SSH_USER     = "SSH_USER"
	SSH_PASSWORD = "SSH_PASSWORD"
	SSH_HOST     = "SSH_HOST"
)
